#==============================================
# Generated On: 01/28/2016
# Generated By: Gary Coburn
# Specialist
# Organization: VMware
# Twitter: @coburnGary
# GuestAgent install script v1
#==============================================
#----------------------------------------------
#==================USAGE=======================
# incomplete
#----------------------------------------------
#===============REQUIREMENTS ===================
# For this script to run successfully be sure:
# 	*To run PowerShell as administrator
#	*To have admin rights on the server
#----------------------------------------------
# ----------------------------------------
# 		CHECK POWERSHELL SESSION
# ----------------------------------------
$Elevated = New-Object Security.Principal.WindowsPrincipal( [Security.Principal.WindowsIdentity]::GetCurrent() )
& {
    if ($Elevated.IsInRole( [Security.Principal.WindowsBuiltInRole]::Administrator ))
    {

        write-host "PowerShell is running as an administrator." -ForegroundColor Green
    } Else {
		throw "Powershell must be run as an adminstrator."
	}

    if( [IntPtr]::size * 8 -eq 64 )
    {
		Write-Host "You are running 64-bit PowerShell" -ForegroundColor Green

    }
    else
    {
		Write-Host "You are running 32-bit PowerShell" -ForegroundColor Red
		Throw "Please run using 64-bit PowerShell as administrator"
    }
}
# ----------------------------------------
# 		END OF POWERSHELL CHECK
# ----------------------------------------


#=============EDITOR'S NOTE====================
# In order for this script to work on servers that
# You will either need .NET 3.5 already installed or access
# to the internet for install purposes.

# ----------------------------------------
#   USER CONFIGURATION - EDIT AS NEEDED
# ----------------------------------------

# incomplete this section will build what the script prompts for later

# ----------------------------------------
# 		END OF USER CONFIGURATION
# ----------------------------------------


# ----------------------------------------
# 		Install Script
# ----------------------------------------

#functions
#Download function called to pull the files
function downloadNeededFiles($url,$file)
{
    "$file Downloading" | Tee-Object -FilePath C:\opt\agentinstall.txt -Append | Write-Host -ForegroundColor Yellow
    [Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
    $clnt = New-Object System.Net.WebClient
    $clnt.DownloadFile($url,$file)
    "$file Downloaded" | Tee-Object -FilePath C:\opt\agentinstall.txt -Append | Write-Host -ForegroundColor Green
}

# Get Installer
"Downloading XAMPP Executable" | Tee-Object -FilePath C:\opt\agentinstall.txt -Append | Write-Host -ForegroundColor Yellow
$url="https://www.apachefriends.org/xampp-files/7.0.1/xampp-win32-7.0.1-0-VC14-installer.exe"
"The full URL is $url" | Tee-Object -FilePath C:\opt\agentinstall.txt -Append | Write-Host -ForegroundColor Green
$file="c:\opt\xampp.exe"
# Call Download Function
downloadNeededFiles $url $file

# Configure Firewall to Open
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False

# Execute the Installer
"Executing: $file" | Tee-Object -FilePath C:\opt\xampp.txt -Append | Write-Host -ForegroundColor Yellow
cd c:\opt
Start-Process $file -ArgumentList " --mode unattended" -PassThru
"$file Executed" | Tee-Object -FilePath C:\opt\xampp.txt -Append | Write-Host -ForegroundColor Green


# ----------------------------------------
# 		Install Script Complete
# ----------------------------------------
